#Organisation level Secrets
#Repository level Secrets
#environment  level Secrets

#go to setting in github and create Secrets


#--------------Repository level Secrets-----------



on : push 
env: 
          CONTAINER_REGISTRY: docker.io
          IMAGE_NAME: github-action-nginx
jobs:
  docker:
    
    runs-on: ubuntu-latest
    steps:
      - name: "Docker Build"        
        run: echo docker build -t $CONTAINER_REGISTRY/$dockerUsername/imageName:latest

      - name: "Docker Login"      
        run: echo docker login --username=$DOCKER_USERNAME --pasword=$DOCKER_PASSWORD

      - name: "Docker Publish"
        
        run: echo docker build -t $CONTAINER_REGISTRY/$dockerUsername/imageName:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Run
      run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest