#You can use expressions to programmatically set environment variables in workflow files and access contexts.
#An expression can be any combination of literal values, references to a context, or functions.

name : exploring variables and Secrets
on : push 
env: 
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: sumit
          IMAGE_NAME: github-action-nginx
jobs:
  docker:
    
    runs-on: ubuntu-latest
    steps:
      - name: "Docker Build"        
        run: echo docker build -t $CONTAINER_REGISTRY/$dockerUsername/imageName:latest

      - name: "Docker Login"
        env:          
          DOCKER_PASSWORD: sumit          
        run: echo docker login --username=$DOCKER_USERNAME --pasword=$DOCKER_PASSWORD

      - name: "Docker Publish"
        
        run: echo docker build -t $CONTAINER_REGISTRY/$dockerUsername/imageName:latest

  deploy:
    if: github.ref == 'ref/heads/main'
    needs: docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Run
      run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

